site_name: ruihan's NoteBook
site_url: https://cybotiger.github.io/note/
site_author: cybotiger

repo_url: https://github.com/cyboTiger/note
repo_name: cyboTiger/note


theme:
  name: material
  features:
    - navigation.tracking  #锚点跟踪
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: zh
  font:
    text: LXGW WenKai GB Screen
    code: JetBrains Mono
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: lime
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: lime

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - attr_list
  - def_list
  - md_in_html
  - sane_lists
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:  #任务列表
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home:
    - index.md
  - 课程笔记:
    - courses/index.md
    - 数据结构基础: courses/FDS/FDS.md
    - 高级数据结构与算法分析:
      - courses/ADS/index.md 
      - lec1 | AVL tree/Splay tree: courses/ADS/ads1.md
      - lec2 | RedBlack tree/B+ tree: courses/ADS/ads2.md
    - 数字逻辑设计: courses/logic/logic.md
    - 数据库系统: 
      - courses/DB/index.md
      - 数据库简介: courses/DB/DB.md
      - 索引: courses/DB/db10.md
      - 查询处理: courses/DB/db11.md
      - MiniSQL: courses/DB/minisql.md
    - 计算机组成: 
      - 第二章 Instruction: courses/CO/2_instruction.md
      - 第三章 Arithmatic: courses/CO/3_arithmatic.md
    - 面向对象: courses/oop/oop.md
    - 计算机网络: courses/network.md
    - 数据要素市场: courses/data_market.md
  - 自学路线:
    - self_learn/index.md
    - CS50-ai: self_learn/ai50/ai50.md
    - CS61A: 
      - self_learn/cs61a/index.md
      - 第一章: self_learn/cs61a/ch1.md
      - 第二章: self_learn/cs61a/ch2.md
      - 第三章: self_learn/cs61a/ch3.md
      - 第四章: self_learn/cs61a/ch4.md
    - CS231n: self_learn/cs231n/cs231n.md
    - 深度学习基础: self_learn/basicDL.md
    - CSAPP: self_learn/csapp.md
    - 数学建模: self_learn/mathmodel.md
    - 托福: self_learn/toefl/resource.md
  - Miscellaneous:
    - quotes: misc/quotes.md
    - 习惯: misc/habit.md
    - 健身: misc/fitness.md
  - Tools:
    - mkdocs使用: tools/mkdocs.md
  - Research:
    - 学习资源: research/resource.md
    - 方法论: research/methodology.md
    - 定期规划: research/roadmap.md
    - survey on efficient/Multimodal LLM: research/survey.md
    - LLaVA: research/llava.md
    - Attention: research/attention.md


extra_javascript:
  - js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # for katex 

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # for katex